version: '2'
services:
  nginx:
      build: ./nginx
      container_name: nginx
      network_mode: "host"
      volumes:
        - ~/project/:/opt/web
        - ~/log:/opt/log
  php:
      build: ./php
      container_name: php
      network_mode: "host"
      volumes:
        - ~/project:/opt/web
  mysql:
      build: ./mysql/file
      container_name: mysql
      network_mode: "host"
      volumes:
        - ~/data/mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: 123456
  redis:
      build: ./redis/file
      container_name: redis
      network_mode: "host"
      volumes:
        - ~/data/redis:/data